server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/securitytest?serverTimezone=Asia/Seoul
    username: security
    password: shvhsy8571@

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 620688255305-i2o71svpjth3vrfijg121fb1a4tiq1fl.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

